apiVersion: apps/v1
kind: Deployment
metadata:
  name:  movella-nginx
  namespace: nginx
  labels:
    app:  movella-nginx
spec:
  selector:
    matchLabels:
      app: movella-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: movella-nginx
    spec:
      containers:
      - name:  nginx
        image:  movella-nginx:alpine-slim
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
          - containerPort:  80
            name:  nginx
      #   volumeMounts:
      #     - mountPath: /etc/nginx/nginx.conf
      #       name: nginx-config
      #       subPath: nginx.conf
      # volumes:
      #   - name: nginx-config
      #     configMap:
      #       name: nginx-config
      #       items:
      #         - key: nginx.conf
      #           path: nginx.conf
      restartPolicy: Always