apiVersion: v1
kind: Service
metadata:
  name: movella-nginx
  namespace: nginx
spec:
  selector:
    app: movella-nginx
  type: NodePort
  ports:
    - name: nginx
      protocol: TCP
      port: 8080
      targetPort: nginx
      nodePort: 30000